Terraformchanges
oracle-devrel/oci-arch-queue-oke-demo pull request #13
Opened 2023-08-12 06:26 UTC by anilcourse

Hi Phil ,

I have created a terraform script and checked in another repo which use source code from here to deploy it as well. 

Terraform will provision the resources , create required policies and deploy code for Function and OKE consumer along with KEDA .

Could you merge/review changes done in this repo please ?

2023-08-16 12:51 UTC, mp3monster requested changes

2023-08-16 12:51 UTC, mp3monster commented on oke-consumer/pom.xml
why comment out rather than remove dependencies?

2023-08-16 12:51 UTC, mp3monster commented on README.md
Rather than eliminate the manual option - separate it out so readers can understand how things work

2023-08-16 12:51 UTC, mp3monster commented on oke-consumer/queue-oke.yaml
should have a better image name than IMAGE_NAME if a value is going to be hardwired

2023-08-16 12:51 UTC, mp3monster commented on oke-consumer/readme.md
suggest keeping this so people can deploy into an existing cluster

2023-08-16 12:51 UTC, mp3monster commented on queue-length-function/pom.xml
as before with commented out dependencies - remove or we should be clear why they're commented out

2023-08-16 12:51 UTC, mp3monster commented on queue-length-function/readme.md
as per prev readme comments

2023-08-18 07:21 UTC, anilcourse commented on oke-consumer/pom.xml
removed commented dependancies.

2023-08-18 07:21 UTC, anilcourse commented on README.md
Done , added another para for manual deployment and added respective readme files.

2023-08-18 07:22 UTC, anilcourse commented on oke-consumer/queue-oke.yaml
I kept it as is since this is just a substitute name which will be replaced by actual image name.

2023-08-18 07:23 UTC, anilcourse commented on oke-consumer/readme.md
Done , added manual deployment option and provided link for manual deployments.

2023-08-18 07:23 UTC, anilcourse commented on queue-length-function/pom.xml
removed commented dependancies.

2023-08-18 07:23 UTC, anilcourse commented on queue-length-function/pom.xml
Done , added manual deployment option and provided link for manual deployments.

2023-08-18 07:23 UTC, anilcourse commented on queue-length-function/readme.md
Done , added manual deployment option and provided link for manual deployments.

2023-08-18 07:24 UTC, anilcourse commented
Hi Phil , I have removed commented dependencies and added option for manual deployment with original readme files.

2023-08-18 08:48 UTC, mp3monster approved these changes

2023-08-18 08:48 UTC, merged